version: '3'

services:
  db:
    image: mysql:5.7  # MySQLのバージョンはプロジェクトの要件に応じて調整してください。
    volumes:
      - db-data:/var/lib/mysql  # MySQLのデータ保存先
    environment:
      MYSQL_ROOT_PASSWORD: password  # rootユーザーのパスワード
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3010:3010"
    depends_on:
      - db

volumes:
  db-data:
    driver: local